import { Platform, StyleSheet } from 'react-native';
import { INTERACTION_TOP, ZOOM_ACTIVE } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#000' },
  nativeCamera: { flex: 1 },
  fallbackContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 },
  fallbackTitle: { color: '#fff', fontSize: 28, fontWeight: '700', marginBottom: 12 },
  fallbackText: { color: 'rgba(255,255,255,0.7)', fontSize: 15, textAlign: 'center' },

  topBar: {
    position: 'absolute',
    top: INTERACTION_TOP,
    left: 12,
    right: 12,
    height: 44,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.42)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsButtonActive: {
    borderColor: '#ff6f9f',
    backgroundColor: 'rgba(255,111,159,0.16)',
  },
  settingsIcon: { color: '#fff', fontSize: 21, fontWeight: '800', marginTop: -10 },
  settingsOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    alignItems: 'flex-start',
    paddingTop: INTERACTION_TOP + 54,
    paddingLeft: 48,
  },
  settingsPanel: {
    width: '86%',
    maxWidth: 360,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    padding: 16,
  },
  settingsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  settingsTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  closeButtonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  settingRow: { gap: 10, marginTop: 12 },
  settingLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 13, fontWeight: '600' },
  aspectOptions: { flexDirection: 'row', gap: 10 },
  aspectBtn: {
    minWidth: 62,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
  },
  aspectBtnActive: { backgroundColor: 'rgba(255,111,159,0.26)', borderColor: '#ff6f9f' },
  aspectBtnText: { color: 'rgba(255,255,255,0.72)', fontSize: 13, fontWeight: '700' },
  aspectBtnTextActive: { color: '#fff' },
  saveFormatOptions: { flexDirection: 'row', gap: 10 },
  saveFormatBtn: {
    flex: 1,
    minHeight: 58,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    justifyContent: 'center',
  },
  saveFormatBtnActive: {
    backgroundColor: 'rgba(255,111,159,0.2)',
    borderColor: '#ff6f9f',
  },
  saveFormatTitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 3,
  },
  saveFormatTitleActive: { color: '#fff' },
  saveFormatSubtitle: {
    color: 'rgba(255,255,255,0.46)',
    fontSize: 10,
    fontWeight: '600',
  },
  saveFormatSubtitleActive: { color: 'rgba(255,255,255,0.8)' },
  rightPanel: {
    position: 'absolute',
    right: 8,
    top: '50%',
    transform: [{ translateY: -170 }],
    justifyContent: 'center',
    alignItems: 'center',
    gap: 14,
    zIndex: 15,
  },
  modeButton: {
    width: 62,
    minHeight: 50,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  modeButtonSelected: {
    backgroundColor: 'transparent',
  },
  modeButtonLabel: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  modeButtonLabelSelected: {
    color: '#ff6f9f',
  },
  modeIcon: { borderColor: 'rgba(255,255,255,0.92)' },
  modeIconSelected: { borderColor: '#ff6f9f' },
  modeIconFill: { backgroundColor: 'rgba(255,255,255,0.9)' },
  modeIconFillSelected: { backgroundColor: '#ff6f9f' },
  beautyIconPortrait: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  beautyIconHair: {
    position: 'absolute',
    left: 5,
    top: 3,
    width: 18,
    height: 22,
    borderTopWidth: 2.4,
    borderLeftWidth: 2.4,
    borderRightWidth: 2.4,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 13,
    transform: [{ rotate: '-10deg' }],
  },
  beautyIconFaceLine: {
    position: 'absolute',
    right: 6,
    top: 7,
    width: 12,
    height: 16,
    borderRightWidth: 2.4,
    borderBottomWidth: 2.4,
    borderBottomRightRadius: 9,
    transform: [{ rotate: '8deg' }],
  },
  beautyIconEye: {
    position: 'absolute',
    right: 12,
    top: 14,
    width: 5,
    height: 2,
    borderTopWidth: 2.2,
    borderRadius: 2,
  },
  beautyIconMouth: {
    position: 'absolute',
    right: 10,
    top: 20,
    width: 7,
    height: 4,
    borderBottomWidth: 2.2,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  beautyIconNeck: {
    position: 'absolute',
    left: 11,
    bottom: 2,
    width: 11,
    height: 5,
    borderBottomWidth: 2.2,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  beautyIconMagic: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  beautyIconWand: {
    position: 'absolute',
    left: 8,
    top: 11,
    width: 18,
    height: 7,
    borderRadius: 4,
    borderWidth: 2.4,
    transform: [{ rotate: '-45deg' }],
  },
  beautyIconWandTip: {
    position: 'absolute',
    right: -4,
    top: -3,
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  beautyIconStarLarge: {
    position: 'absolute',
    right: 4,
    top: 2,
    width: 9,
    height: 9,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    transform: [{ rotate: '45deg' }],
  },
  beautyIconStarSmall: {
    position: 'absolute',
    left: 3,
    top: 4,
    width: 6,
    height: 6,
    borderTopWidth: 1.8,
    borderLeftWidth: 1.8,
    transform: [{ rotate: '45deg' }],
  },
  settingsRailIcon: {
    width: 31,
    height: 30,
    justifyContent: 'center',
    gap: 5,
  },
  settingsRailSlider: {
    width: 30,
    height: 0,
    borderTopWidth: 2,
    borderRadius: 1,
  },
  settingsRailKnobLeft: {
    position: 'absolute',
    left: 4,
    top: -5,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  settingsRailKnobRight: {
    position: 'absolute',
    right: 4,
    top: -5,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  settingsRailKnobCenter: {
    position: 'absolute',
    left: 13,
    top: -5,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  cameraIconBody: {
    width: 25,
    height: 18,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraIconLens: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
  },
  cameraIconDot: {
    position: 'absolute',
    left: 4,
    top: -4,
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  cameraIconDotRight: { left: undefined, right: 4 },
  pipIconFrame: {
    width: 27,
    height: 21,
    borderRadius: 5,
    borderWidth: 2,
  },
  pipIconInset: {
    position: 'absolute',
    right: 3,
    top: 3,
    width: 9,
    height: 9,
    borderRadius: 2,
  },
  pipIconInsetCircle: { borderRadius: 4.5 },
  splitIconFrame: {
    width: 27,
    height: 21,
    borderRadius: 5,
    borderWidth: 2,
    overflow: 'hidden',
  },
  splitIconLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '50%',
  },
  splitIconTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '50%',
  },
  splitIconDividerVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: 2,
    marginLeft: -1,
    borderLeftWidth: 2,
  },
  splitIconDividerHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
    height: 2,
    marginTop: -1,
    borderTopWidth: 2,
  },
  disabledControl: { opacity: 0.38 },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingBottom: Platform.OS === 'ios' ? 44 : 32,
    paddingTop: 16,
    paddingHorizontal: 20,
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 4,
    width: 118,
  },
  modeBtn: { flex: 1, paddingVertical: 6, alignItems: 'center', borderRadius: 16 },
  modeBtnActive: { backgroundColor: 'rgba(255,255,255,0.25)' },
  modeBtnText: { color: '#aaa', fontSize: 12, fontWeight: '600' },
  modeBtnTextActive: { color: '#fff', fontWeight: '700' },
  shutterOuter: {
    width: 78,
    height: 78,
    borderRadius: 39,
    overflow: 'hidden',
    backgroundColor: '#ff6fa8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterOuterMuted: { opacity: 0.5 },
  shutterOuterLocked: {
    backgroundColor: 'rgba(18,18,18,0.72)',
    borderColor: 'rgba(255,255,255,0.86)',
  },
  shutterOuterVideoReady: {},
  shutterOuterRecording: {},
  shutterRingImage: {
    ...StyleSheet.absoluteFillObject,
    width: 78,
    height: 78,
  },
  shutterCore: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterInner: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#fff' },
  shutterInnerVideoReady: { backgroundColor: '#ff3b30' },
  shutterInnerRecording: { width: 28, height: 28, borderRadius: 6, backgroundColor: '#ff373c' },
  videoLockBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoLockShackle: {
    position: 'absolute',
    top: 9,
    width: 14,
    height: 13,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
    borderWidth: 2,
    borderBottomWidth: 0,
    borderColor: '#fff',
  },
  videoLockBody: {
    width: 18,
    height: 14,
    marginTop: 10,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  lockIcon: {
    width: 34,
    height: 38,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  lockIconShackle: {
    position: 'absolute',
    top: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 4,
    borderColor: '#fff',
    borderBottomColor: 'transparent',
  },
  lockIconBody: {
    width: 30,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  flipBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  flipBtnActive: { borderColor: '#4da6ff', backgroundColor: 'rgba(77,166,255,0.25)' },
  flipIcon: {
    width: 34,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flipIconTone: { borderColor: 'rgba(255,255,255,0.82)' },
  flipIconActive: { borderColor: '#9cccff' },
  flipCameraBody: {
    width: 27,
    height: 19,
    borderRadius: 6,
    borderWidth: 2.4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flipCameraLens: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 2.2,
  },
  flipCameraDot: {
    position: 'absolute',
    right: 4,
    top: 4,
    width: 3,
    height: 3,
    borderRadius: 1.5,
    borderWidth: 1.5,
  },
  flipArrowTop: {
    position: 'absolute',
    right: 0,
    top: 2,
    width: 12,
    height: 8,
    borderTopWidth: 2.2,
    borderRightWidth: 2.2,
    borderTopRightRadius: 7,
    transform: [{ rotate: '10deg' }],
  },
  flipArrowTopHead: {
    position: 'absolute',
    right: 8,
    top: 0,
    width: 7,
    height: 7,
    borderLeftWidth: 2.2,
    borderTopWidth: 2.2,
    transform: [{ rotate: '-38deg' }],
  },
  flipArrowBottom: {
    position: 'absolute',
    left: 0,
    bottom: 2,
    width: 12,
    height: 8,
    borderBottomWidth: 2.2,
    borderLeftWidth: 2.2,
    borderBottomLeftRadius: 7,
    transform: [{ rotate: '10deg' }],
  },
  flipArrowBottomHead: {
    position: 'absolute',
    left: 8,
    bottom: 0,
    width: 7,
    height: 7,
    borderRightWidth: 2.2,
    borderBottomWidth: 2.2,
    transform: [{ rotate: '-38deg' }],
  },

  zoomDialOverlay: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomPill: {
    width: 48,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.46)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomPillCompact: {
    width: 40,
    height: 28,
    borderRadius: 14,
  },
  zoomPillText: { color: ZOOM_ACTIVE, fontSize: 15, fontWeight: '800' },
  zoomPillTextCompact: { fontSize: 13 },

  dividerVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    alignItems: 'center',
  },
  dividerLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  dividerHitVertical: {
    position: 'absolute',
    top: '50%',
    marginTop: -32,
    width: 56,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerHandleVertical: {
    width: 36,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
  },
  dividerHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    alignItems: 'center',
  },
  dividerLineHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  dividerHitHorizontal: {
    // Mirror the vertical handle: center the 56px hit area on the 1px line.
    // left: '50%' + marginLeft: -32 -> horizontal center
    // top: -27 ~= -(hitHeight/2 - lineHeight/2) = -(56/2 - 1/2) -> vertical center on line
    position: 'absolute',
    left: '50%',
    marginLeft: -32,
    top: -27,
    width: 64,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerHandleHorizontal: {
    width: 44,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
  },
  dividerHitActive: { transform: [{ scale: 1.12 }] },
  dividerHandleActive: { backgroundColor: '#4da6ff' },
  dividerHandleText: { color: '#000', fontSize: 13, fontWeight: '900' },

  mediaPermissionOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: 'rgba(0,0,0,0.36)',
  },
  mediaPermissionCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    backgroundColor: 'rgba(28,28,30,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  mediaBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: Platform.OS === 'ios' ? 140 : 130,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  mediaBannerText: { flex: 1, color: '#fff', fontSize: 13 },
  secondaryButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  secondaryButtonLabel: { color: '#000', fontSize: 13, fontWeight: '600' },
  unlockOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  unlockScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.46)',
  },
  unlockCard: {
    width: '100%',
    maxWidth: 372,
    minHeight: 414,
    paddingHorizontal: 24,
    paddingTop: 54,
    paddingBottom: 22,
    borderRadius: 34,
    alignItems: 'center',
    backgroundColor: 'rgba(250,250,252,0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 16 },
  },
  unlockCloseIconButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(120,120,128,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  unlockCloseIconText: { color: 'rgba(60,60,67,0.58)', fontSize: 30, lineHeight: 32, fontWeight: '300' },
  unlockIconWrap: {
    width: 92,
    height: 68,
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unlockRecorderFrame: {
    width: 82,
    height: 54,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#42474c',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  unlockRecorderLeftPane: {
    position: 'absolute',
    left: 12,
    top: 18,
    width: 18,
    height: 16,
    borderRadius: 4,
    backgroundColor: '#42474c',
  },
  unlockRecorderDivider: {
    position: 'absolute',
    left: 40,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#42474c',
  },
  unlockRecorderRecDot: {
    position: 'absolute',
    right: 17,
    top: 20,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ff3b30',
  },
  unlockDivider: {
    alignSelf: 'stretch',
    height: 1,
    marginTop: 22,
    marginBottom: 24,
    backgroundColor: 'rgba(60,60,67,0.14)',
  },
  unlockSheet: {
    marginHorizontal: 16,
    marginBottom: Platform.OS === 'ios' ? 34 : 20,
    padding: 20,
    borderRadius: 24,
    backgroundColor: 'rgba(246,246,246,0.96)',
  },
  unlockTitle: { color: '#111', fontSize: 26, fontWeight: '800', marginBottom: 14, textAlign: 'center' },
  unlockBody: { color: 'rgba(60,60,67,0.68)', fontSize: 18, lineHeight: 26, textAlign: 'center' },
  unlockPrimaryButton: {
    alignSelf: 'stretch',
    height: 62,
    borderRadius: 22,
    backgroundColor: '#ffd33d',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#d6a900',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  unlockPrimaryText: { color: '#050505', fontSize: 18, fontWeight: '900', textAlign: 'center' },
  unlockWaiting: {
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  unlockWaitingText: { color: 'rgba(60,60,67,0.64)', fontSize: 18, fontWeight: '600', textAlign: 'center' },
  unlockErrorText: {
    color: '#c9342f',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
    textAlign: 'center',
  },
  unlockRetryButton: {
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(60,60,67,0.08)',
  },
  unlockRetryText: { color: '#333', fontSize: 14, fontWeight: '700' },
  unlockTextButton: {
    alignSelf: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginTop: 10,
  },
  unlockTextButtonLabel: { color: 'rgba(60,60,67,0.42)', fontSize: 15, fontWeight: '700' },
  unlockCloseButton: {
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  unlockCloseText: { color: '#333', fontSize: 15, fontWeight: '700' },
  savingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  recordingIndicator: {
    position: 'absolute',
    top: INTERACTION_TOP,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  recordingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#ff4444' },
  recordingText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  audioIndicator: {
    position: 'absolute',
    top: INTERACTION_TOP,
    left: 66,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  audioLabel: { color: '#aaa', fontSize: 11, fontWeight: '600' },
  audioBars: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, height: 16 },
  audioBar: {
    width: 3,
    height: 4,
    borderRadius: 1.5,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  audioBarActive: { backgroundColor: '#4dff4d' },

  beautyOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 30,
    elevation: 30,
  },
  beautyDismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  beautyPanel: {
    marginHorizontal: 0,
    marginBottom: 0,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 14,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 26 : 20,
    backgroundColor: 'rgba(18,20,23,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: -8 },
  },
  beautyHeader: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  beautyHeaderSide: { width: 72 },
  beautyTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  beautyResetButton: {
    width: 72,
    height: 28,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  beautyResetText: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 12,
    fontWeight: '600',
  },
  beautyHint: {
    marginTop: 4,
    color: 'rgba(255,255,255,0.48)',
    fontSize: 12,
    textAlign: 'center',
  },
  beautySliderWrap: {
    marginTop: 12,
    marginHorizontal: 22,
    marginBottom: 4,
    paddingHorizontal: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  beautySliderValue: {
    color: '#fff',
    width: 34,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  beautySliderTrack: {
    flex: 1,
    height: 26,
    justifyContent: 'center',
  },
  beautySliderRail: {
    height: 3,
    borderRadius: 1.5,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  beautySliderFill: {
    position: 'absolute',
    left: 0,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#ff6f9f',
  },
  beautySliderThumb: {
    position: 'absolute',
    top: 3,
    width: 20,
    height: 20,
    marginLeft: -10,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  beautyItems: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    paddingHorizontal: 0,
    paddingTop: 10,
  },
  beautyItem: {
    flex: 1,
    minHeight: 82,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  beautyItemSelected: {
    backgroundColor: 'rgba(255,111,159,0.07)',
    borderColor: '#ff6f9f',
  },
  beautyItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  beautyItemIconSelected: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  beautyItemIconImage: {
    width: 30,
    height: 30,
    tintColor: 'rgba(255,255,255,0.82)',
  },
  beautyItemIconImageSelected: {
    width: 32,
    height: 32,
    tintColor: '#ff6f9f',
  },
  beautyItemIconGlyph: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
    textAlign: 'center',
  },
  beautyItemIconGlyphSelected: {
    color: '#ff6f9f',
    fontSize: 30,
    lineHeight: 34,
  },
  beautyItemLabel: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 13,
    fontWeight: '700',
  },
  beautyItemLabelSelected: {
    color: '#ff6f9f',
  },

  centered: { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  permissionWaitingText: { marginTop: 14, color: 'rgba(255,255,255,0.72)', fontSize: 15, fontWeight: '600' },
  permissionScreen: { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  permissionCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    backgroundColor: 'rgba(28,28,30,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  permissionIcon: {
    width: 64,
    height: 64,
    borderRadius: 20,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  permissionCameraBody: {
    width: 36,
    height: 25,
    borderRadius: 7,
    borderWidth: 3,
    borderColor: '#fff',
  },
  permissionCameraLens: {
    position: 'absolute',
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 3,
    borderColor: '#fff',
  },
  permissionTitle: { color: '#fff', fontSize: 22, fontWeight: '800', marginBottom: 10, textAlign: 'center' },
  permissionBody: { color: 'rgba(255,255,255,0.72)', fontSize: 16, textAlign: 'center', marginBottom: 22, lineHeight: 23 },
  primaryButton: { minWidth: 156, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 999, backgroundColor: '#fff' },
  primaryButtonLabel: { color: '#000', fontSize: 16, fontWeight: '700', textAlign: 'center' },
  systemPermissionCard: {
    width: '100%',
    maxWidth: 398,
    borderRadius: 34,
    paddingHorizontal: 34,
    paddingTop: 32,
    paddingBottom: 22,
    backgroundColor: 'rgba(238,238,238,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
  },
  systemPermissionIcon: {
    width: 66,
    height: 66,
    borderRadius: 18,
    marginBottom: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(80,80,84,0.32)',
  },
  permissionCameraBodyDark: {
    width: 36,
    height: 25,
    borderRadius: 7,
    backgroundColor: '#fff',
  },
  permissionCameraLensDark: {
    position: 'absolute',
    right: 11,
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 3,
    borderColor: 'rgba(80,80,84,0.9)',
  },
  systemPermissionTitle: {
    color: '#050505',
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  systemPermissionBody: {
    color: 'rgba(0,0,0,0.62)',
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '600',
    marginBottom: 24,
  },
  systemPermissionActions: {
    flexDirection: 'row',
    gap: 12,
  },
  systemPermissionButton: {
    flex: 1,
    height: 58,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(150,150,150,0.36)',
  },
  systemPermissionButtonText: {
    color: '#050505',
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  photosPermissionIcon: {
    width: 66,
    height: 66,
    borderRadius: 16,
    marginBottom: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  photosPetalRed: {
    position: 'absolute',
    top: 8,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#ff3b30',
  },
  photosPetalOrange: {
    position: 'absolute',
    right: 12,
    top: 14,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#ff9500',
    transform: [{ rotate: '55deg' }],
  },
  photosPetalYellow: {
    position: 'absolute',
    right: 12,
    bottom: 14,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#ffcc00',
    transform: [{ rotate: '125deg' }],
  },
  photosPetalGreen: {
    position: 'absolute',
    bottom: 8,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#34c759',
  },
  photosPetalBlue: {
    position: 'absolute',
    left: 12,
    bottom: 14,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#007aff',
    transform: [{ rotate: '55deg' }],
  },
  photosPetalPurple: {
    position: 'absolute',
    left: 12,
    top: 14,
    width: 17,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#af52de',
    transform: [{ rotate: '125deg' }],
  },
});
