import { Platform, StyleSheet } from 'react-native';
import { INTERACTION_TOP, ZOOM_ACTIVE } from './constants';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#000' },
  nativeCamera: { flex: 1 },
  fallbackContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 },
  fallbackTitle: { color: '#fff', fontSize: 28, fontWeight: '700', marginBottom: 12 },
  fallbackText: { color: 'rgba(255,255,255,0.7)', fontSize: 15, textAlign: 'center' },

  topBar: {
    position: 'absolute',
    top: INTERACTION_TOP,
    left: 12,
    right: 12,
    height: 44,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsIcon: { color: '#fff', fontSize: 20, fontWeight: '800', marginTop: -8 },
  settingsOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.28)',
    alignItems: 'center',
    paddingTop: INTERACTION_TOP + 54,
  },
  settingsPanel: {
    width: '84%',
    maxWidth: 360,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.74)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    padding: 16,
  },
  settingsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  settingsTitle: { color: '#fff', fontSize: 16, fontWeight: '700' },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  closeButtonText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  settingRow: { gap: 10 },
  settingLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 13, fontWeight: '600' },
  aspectOptions: { flexDirection: 'row', gap: 8 },
  aspectBtn: {
    minWidth: 62,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
  },
  aspectBtnActive: { backgroundColor: 'rgba(77,166,255,0.42)', borderColor: '#4da6ff' },
  aspectBtnText: { color: 'rgba(255,255,255,0.72)', fontSize: 13, fontWeight: '700' },
  aspectBtnTextActive: { color: '#fff' },

  rightPanel: {
    position: 'absolute',
    right: 12,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    gap: 14,
  },
  modeButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0,0,0,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  modeButtonSelected: {
    borderColor: '#4da6ff',
    backgroundColor: 'rgba(77,166,255,0.18)',
    shadowColor: '#4da6ff',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
  },
  modeIcon: { borderColor: 'rgba(255,255,255,0.58)' },
  modeIconSelected: { borderColor: '#7bb7ff' },
  modeIconFill: { backgroundColor: 'rgba(255,255,255,0.48)' },
  modeIconFillSelected: { backgroundColor: '#7bb7ff' },
  cameraIconBody: {
    width: 25,
    height: 18,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraIconLens: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
  },
  cameraIconDot: {
    position: 'absolute',
    left: 4,
    top: -4,
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  cameraIconDotRight: { left: undefined, right: 4 },
  pipIconFrame: {
    width: 27,
    height: 21,
    borderRadius: 5,
    borderWidth: 2,
  },
  pipIconInset: {
    position: 'absolute',
    right: 3,
    top: 3,
    width: 9,
    height: 9,
    borderRadius: 2,
  },
  pipIconInsetCircle: { borderRadius: 4.5 },
  splitIconFrame: {
    width: 27,
    height: 21,
    borderRadius: 5,
    borderWidth: 2,
    overflow: 'hidden',
  },
  splitIconLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '50%',
  },
  splitIconTop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '50%',
  },
  splitIconDividerVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: '50%',
    width: 2,
    marginLeft: -1,
    borderLeftWidth: 2,
  },
  splitIconDividerHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
    height: 2,
    marginTop: -1,
    borderTopWidth: 2,
  },
  disabledControl: { opacity: 0.38 },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingBottom: Platform.OS === 'ios' ? 44 : 32,
    paddingTop: 16,
    paddingHorizontal: 20,
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    padding: 4,
    width: 118,
  },
  modeBtn: { flex: 1, paddingVertical: 6, alignItems: 'center', borderRadius: 16 },
  modeBtnActive: { backgroundColor: 'rgba(255,255,255,0.25)' },
  modeBtnText: { color: '#aaa', fontSize: 12, fontWeight: '600' },
  modeBtnTextActive: { color: '#fff', fontWeight: '700' },
  shutterOuter: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shutterOuterMuted: { opacity: 0.5 },
  shutterOuterRecording: { borderColor: '#ff4444' },
  shutterInner: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#fff' },
  shutterInnerRecording: { width: 28, height: 28, borderRadius: 6, backgroundColor: '#ff4444' },
  flipBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  flipBtnActive: { borderColor: '#4da6ff', backgroundColor: 'rgba(77,166,255,0.25)' },
  flipBtnText: { color: '#ccc', fontSize: 24, fontWeight: '700' },

  zoomDialOverlay: {
    position: 'absolute',
    alignItems: 'center',
  },
  singleZoomPosition: { left: 0, right: 0, bottom: Platform.OS === 'ios' ? 132 : 120 },
  splitZoomPosition: { bottom: Platform.OS === 'ios' ? 132 : 120, alignItems: 'center' },
  sxTopZoomPosition: { left: 0, right: 0 },
  sxBottomZoomPosition: { left: 0, right: 0, bottom: Platform.OS === 'ios' ? 132 : 120 },
  pipZoomPosition: { alignItems: 'center' },
  zoomDial: {
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  zoomDialCompact: { paddingHorizontal: 5, paddingVertical: 4, borderRadius: 16 },
  zoomPresetRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  zoomPreset: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomPresetCompact: { width: 28, height: 28, borderRadius: 14 },
  zoomPresetActive: { backgroundColor: ZOOM_ACTIVE, borderColor: ZOOM_ACTIVE },
  zoomPresetText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  zoomPresetTextCompact: { fontSize: 10 },
  zoomMiniBadge: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomMiniBadgeText: { color: '#fff', fontSize: 11, fontWeight: '800' },
  zoomPresetTextActive: { color: '#000' },
  zoomSlider: {
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.68)',
    alignItems: 'center',
  },
  zoomSliderTrack: {
    width: '100%',
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  zoomSliderFill: { height: 4, borderRadius: 2, backgroundColor: ZOOM_ACTIVE },
  zoomSliderValue: { marginTop: 6, color: '#fff', fontSize: 11, fontWeight: '700' },

  dividerVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    alignItems: 'center',
  },
  dividerLineVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  dividerHitVertical: {
    position: 'absolute',
    top: '50%',
    marginTop: -32,
    width: 56,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerHandleVertical: {
    width: 36,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
  },
  dividerHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    alignItems: 'center',
  },
  dividerLineHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  dividerHitHorizontal: {
    // Mirror the vertical handle: center the 56px hit area on the 1px line.
    // left: '50%' + marginLeft: -32 -> horizontal center
    // top: -27 ~= -(hitHeight/2 - lineHeight/2) = -(56/2 - 1/2) -> vertical center on line
    position: 'absolute',
    left: '50%',
    marginLeft: -32,
    top: -27,
    width: 64,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerHandleHorizontal: {
    width: 44,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.86)',
  },
  dividerHitActive: { transform: [{ scale: 1.12 }] },
  dividerHandleActive: { backgroundColor: '#4da6ff' },
  dividerHandleText: { color: '#000', fontSize: 13, fontWeight: '900' },

  mediaBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: Platform.OS === 'ios' ? 140 : 130,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  mediaBannerText: { flex: 1, color: '#fff', fontSize: 13 },
  secondaryButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fff',
  },
  secondaryButtonLabel: { color: '#000', fontSize: 13, fontWeight: '600' },
  savingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  recordingIndicator: {
    position: 'absolute',
    top: INTERACTION_TOP,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  recordingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#ff4444' },
  recordingText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  audioIndicator: {
    position: 'absolute',
    top: INTERACTION_TOP,
    left: 66,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  audioLabel: { color: '#aaa', fontSize: 11, fontWeight: '600' },
  audioBars: { flexDirection: 'row', alignItems: 'flex-end', gap: 2, height: 16 },
  audioBar: {
    width: 3,
    height: 4,
    borderRadius: 1.5,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  audioBarActive: { backgroundColor: '#4dff4d' },

  centered: { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  permissionTitle: { color: '#fff', fontSize: 20, fontWeight: '700', marginBottom: 8, textAlign: 'center' },
  permissionBody: { color: 'rgba(255,255,255,0.75)', fontSize: 15, textAlign: 'center', marginBottom: 20, lineHeight: 22 },
  primaryButton: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 999, backgroundColor: '#fff' },
  primaryButtonLabel: { color: '#000', fontSize: 16, fontWeight: '600' },
});
